package jason.hermes.capabilities.bioinspiredProtocols.enums;

public enum BioinspiredStageEnum {

    TRANSFER_REQUEST,

    RECEIVE_TRANSFER_REQUEST,

    RESPONSE_TO_TRANSFER,

    RECEIVE_RESPONSE_TO_TRANSFER,

    CONTENT_TRANSFER,

    RECEIVE_CONTENT_TRANSFER,

    CONFIRMATION_TRANSFER,

    RECEIVE_CONFIRMATION_TRANSFER,

    FINISHED;


}
